























# Generated by Django 5.1.3 on 2024-12-01 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, default=19.25, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mht', models.IntegerField()),
                ('mtva', models.IntegerField()),
                ('mttc', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=1)),
                ('tva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tva')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price_ht', models.IntegerField()),
                ('price_ttc', models.IntegerField()),
                ('price_tva', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
                ('lp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lineprice')),
                ('tva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tva')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvment',
            fields=[
                ('id_mouv', models.AutoField(primary_key=True, serialize=False)),
                ('regis_num', models.CharField(max_length=50)),
                ('brand_vehicule', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(max_length=50)),
                ('id_card_num', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('I', 'IN'), ('O', 'OUT')], default='I', max_length=1)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
                ('r_mouv', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mouvment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicletype')),
            ],
        ),
    ]
