# Generated by Django 5.1.3 on 2024-12-01 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvment',
            name='is_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mouvment',
            name='r_mouv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mouvment'),
        ),
    ]
