# Generated by Django 5.1.3 on 2024-12-03 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mouvment_is_stock_alter_mouvment_r_mouv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvment',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invoice'),
        ),
    ]
