# Generated by Django 5.1.3 on 2024-12-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mouvment_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvment',
            name='is_stock',
            field=models.BooleanField(default=True),
        ),
    ]
